version: "3.8"

services:
  php-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: optionret_php82_prod
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    ports:
      - "9008:9000"
    environment:
      PHP_MEMORY_LIMIT: 512M
      PHP_MAX_EXECUTION_TIME: 120
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: moneynci
      DB_USERNAME: debian
      DB_PASSWORD: /y5*(5f(5A6qJp[c
    depends_on:
      - db
      - browsershot
    restart: unless-stopped

  php-test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: optionret_php82_test
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    ports:
      - "9009:9000"
    environment:
      PHP_MEMORY_LIMIT: 512M
      PHP_MAX_EXECUTION_TIME: 120
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: moneynci_test
      DB_USERNAME: debian
      DB_PASSWORD: /y5*(5f(5A6qJp[c
    depends_on:
      - db
      - browsershot
    restart: unless-stopped

  browsershot:
    image: browserless/chrome:latest
    container_name: browsershot
    environment:
      CONNECTION_TIMEOUT: 60000
      MAX_CONCURRENT_SESSIONS: 2
    restart: unless-stopped

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: unless-stopped
    ports:
      - "8082:8080"

  db:
    image: mysql:8.0
    container_name: moneynci_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: moneynci
      MYSQL_USER: debian
      MYSQL_PASSWORD: /y5*(5f(5A6qJp[c
    # en prod tu peux ne pas exposer 3306
    volumes:
      - db_data_prod:/var/lib/mysql

volumes:
  db_data_prod:
