version: "3.8"

services:
  php-prod:
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: moneynci_prod_local
      DB_USERNAME: debian
      DB_PASSWORD: password
    volumes:
      - ./.env.local:/var/www/html/.env:ro
    depends_on:
      - db
      - browsershot

  php-test:
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: moneynci_local
      DB_USERNAME: debian
      DB_PASSWORD: password
    volumes:
      - ./.env.local:/var/www/html/.env:ro
    depends_on:
      - db
      - browsershot

  nginx:
    image: nginx:alpine
    container_name: optionret_nginx
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - php-test
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: moneynci_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: moneynci_local
      MYSQL_USER: debian
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
